
#datasource specific properties
spring: 
  datasource:
    username: root
    password: abcd
    url: jdbc:mysql://mysqlcontainer:3306/ecommdb
  ##jpa properties

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true


message: In production profile
#Feign URLs for other services
product-inventory:
  service:
     url: http://product-inventory:8087